// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export interface Record {
    "id": string;
    "text": string;
    "preview": string;
    "hash": string;
    "copiedAt": time$0.Time;
    "lastUsedAt": time$0.Time;
    "useCount": number;
    "pinned": boolean;
}
