// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ClearHistory(): $CancellablePromise<void> {
    return $Call.ByID(2280397244);
}

export function CopyHistory(id: string): $CancellablePromise<void> {
    return $Call.ByID(2846445306, id);
}

export function DeleteHistory(id: string): $CancellablePromise<void> {
    return $Call.ByID(2279046840, id);
}

export function ListHistory(query: string): $CancellablePromise<$models.clipboardRecord[] | null> {
    return $Call.ByID(1943935317, query);
}
