// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as history$0 from "./internal/history/models.js";

export interface appConfig {
    "history": historyConfig;
    "hotkeys": hotkeyConfig;
    "parsers": parserConfig;
    "translation": translationConfig;
}

export type clipboardRecord = history$0.Record;

export interface historyConfig {
    "maxItems": number;
}

export interface hotkeyConfig {
    "openPanel": string;
    "pasteLatest": string;
    "copyShortcut": string;
}

export interface parserConfig {
    "enabled": { [_ in string]?: boolean } | null;
}

export interface translationConfig {
    "provider": string;
    "targetLanguage": string;
}
